version: '3.9'

services:
  # 🗄 PostgreSQL Database
  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # 🔹 Products Service
  products-service:
    build:
      context: .
      dockerfile: apps/products-service/Dockerfile
    container_name: products-service
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: user
      DB_PASS: password
      DB_NAME: productsdb
    depends_on:
      - postgres
    ports:
      - "3001:3000"  # container port → host port mapping

  # 🔹 Orders Service
  orders-service:
    build:
      context: .
      dockerfile: apps/orders-service/Dockerfile
    container_name: orders-service
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: user
      DB_PASS: password
      DB_NAME: ordersdb
    depends_on:
      - postgres
    ports:
      - "3002:3000"

  # 🌉 API Gateway
  api-gateway:
    build:
      context: .
      dockerfile: apps/api-gateway/Dockerfile
    container_name: api-gateway
    environment:
      PRODUCTS_SERVICE_HOST: products-service
      PRODUCTS_SERVICE_PORT: 3001
      ORDERS_SERVICE_HOST: orders-service
      ORDERS_SERVICE_PORT: 3002
      JWT_SECRET: supersecret
    depends_on:
      - products-service
      - orders-service
    ports:
      - "3000:3000"  

volumes:
  postgres_data: