// apps/frontend/src/app/layout.tsx
import './global.css';
import { Navbar } from '../components/Navbar';

export const metadata = {
  title: 'Welcome to the Microservices Frontend',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-gray-100">
        <Navbar />
        <main className="container mx-auto p-6">{children}</main>
      </body>
    </html>
  );
}